CREATE TABLE if not exists `AbeyanceEventObj` (
`pk`	INTEGER,
`descContent`	TEXT,
`abeyanceTypeName`	TEXT,
`title`	TEXT,
`msgType`	TEXT,
`status`	TEXT,
`sourceId`	TEXT,
`linkUrl`	TEXT,
`summaryInfo`	TEXT,
`publisherId`	TEXT,
`todoUserId`	TEXT,
`creationDate`	TEXT,
`sourceApp`	TEXT,
`sourceAppId`	TEXT,
`sourceAppName`	TEXT,
`sourceAppLogo`	TEXT,
`isRead`	TEXT,
`isHadRead`	INTEGER,
`yzg_ticket`	TEXT,
`isNew`	INTEGER,
`abeyanceId`	TEXT,
`total`	TEXT,
`createdTime`	TEXT,
`fldsubject`	TEXT,
PRIMARY KEY(`pk`)
);
